project:
  type: website
  output-dir: _site

website:
  title: "統計學習理論"
  
  repo-url: https://github.com/wwwh0225/elements-of-statistical-learning
  repo-actions: [edit, issue]
  
  page-footer:
      right: |
        Powered by
        [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)


  sidebar:
    title: "統計學習理論"
    logo: images/statlearn.png
    pinned: true
    align: center
    style: "docked"
    search: true    
    contents:
      - section: "Chapter 2."
        contents:
        - href: Ch2/Sec2.3.ipynb
          text: "2.3 Two Simple Approaches to Prediction"

      - section: "Chapter 4."
        contents:
        - href: Ch4/Sec4.2.ipynb
          text: "4.2 Linear Regression of an Indicator Matrix"
        - href: Ch4/Sec4.3.ipynb
          text: "4.3 Linear Discriminant Analysis"
        - href: Ch4/Sec4.4.ipynb
          text: "4.4 Logistic Regression"

      - section: "Chapter 5."
        contents:
        - href: Ch5/Sec5.1.ipynb
          text: "5.1 Introduction"
        - href: Ch5/Sec5.2.ipynb
          text: "5.2 Piecewise Polynomials and Spl"
        - href: Ch5/Sec5.4.ipynb
          text: "5.4 Smoothing Splines"
        - href: Ch5/Sec5.5.ipynb
          text: "5.5 Automatic Selection of the Smoothing Parameters"
         
      - section: "Chapter 14."
        contents:
        - href: Ch14/Sec14.5.ipynb
          text: "14.5 Principal Components, Curves and Surfaces"



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fontsize: 0.9em
    linestretch: 1.5



